### PR TITLE
QA Fixes

### LINKED ISSUE #50: thematic_with_theme() "replays" htmlwidgets
Notice how the plotly graph gets printed after exiting the following shiny app: 

```r
library(plotly)
library(thematic)
library(shiny)

ui <- fluidPage(
  tags$head(
    tags$style(HTML("body{background-color:black; color:white}")),
    tags$style(HTML("a{color:#008000}"))
  ),
  plotlyOutput("ggplot")
)
server <- function(input, output) {
  output$ggplot <- renderPlotly({
    thematic_with_theme(
      thematic_theme(),
      ggplotly(qplot(1:15, 1:15, color = 1:15))
    )
  })
}
shinyApp(ui, server)
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #50 and #51

### CODE REVIEW

File: R/auto.R [hunk 1]
```diff
@@ -384,6 +384,7 @@ size_to_scale <- function(size, pointsize = 12) {
 
 rs_font_spec <- function() {
   if (!is_rstudio()) return(NULL)
+  if (!"RStudioGD" %in% .Device) return(NULL)
```
Comment (cpsievert) [inline R/auto.R:387]: Let's make sure it's the same on cloud and RSP
