### PR TITLE
don't fail if default device isn't usable & avoid device leakage

### LINKED ISSUE #67: Calling thematic_on() with null device opens new device
Minimal example:

```r

dev.cur()
#> null device 
#> 1 
thematic_on("black", "white")
dev.cur()
#> quartz 
#> 2 
```

This is especially problematic for hosted environments like shinyapps.io that don't have their `getOption("device")` properly set to reflect it's capabilities, leading to the following error:

```r
library(shiny)
thematic::thematic_on("black", "white")
ui <- fluidPage(
  plotOutput("p")
)
server <- function(input, output, session) {
  output$p <- renderPlot(hist(1:10))
}
shinyApp(ui, server)
```

```r
Error: cannot open file 'Rplots.pdf'
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #67

## Testing notes

Install `remotes::install_github("rstudio/thematic")` and run the following app. Before this fix, you'd just see an error message in the app. Now you should see a plot (errors and warnings in the console are OK).

```r
library(shiny)
thematic::thematic_shiny(font = "auto")
opts <- options(device = function() stop("boom"))
onStop(function() options(opts))
ui <- fluidPage(
  tags$style(HTML("body{background:black; color:white}")),
  plotOutput("p")
)
server <- function(input, output, session) {
  output$p <- renderPlot(plot(1:10))
}
shinyApp(ui, server)
```

### CODE REVIEW

File: R/base.R [hunk 1]
```diff
@@ -65,7 +65,7 @@ with_no_new_device <- function(..., fun) {
   dev_after <- dev.cur()
   if (dev_before != dev_after) {
     dev.off(dev_after)
-    dev.set(dev_before)
+    if (dev_before > 1) dev.set(dev_before)
```
Comment (cpsievert) [inline R/base.R:68]: `dev.set()` doesn't do what you'd expect it to when `dev_before` is the `null device`. Here's a mini example:

```r
de> dev.cur()
null device 
          1 
> par("bg")
[1] "transparent"
> dev.cur()
quartz 
     2 
> dev.off()
null device 
          1 
> dev.cur()
null device 
          1 
> dev.set(1)
null device 
          1 
> dev.cur()
quartz 
     2 
```

Looks as though I've come across this issue before in similar `with_device()`-like context:

https://github.com/rstudio/thematic/blob/c05ca534c7d1734fb9a782804980c998ff3457b3/R/hooks.R#L158-L169

File: R/utils.R [hunk 2]
```diff
@@ -83,10 +83,90 @@ is_rstudio <- function(version_needed = NULL) {
...
-in_rstudio_gd <- function(dev_name = names(infer_device())) {
+in_rstudio_gd <- function(dev_name = infer_device()) {
   "RStudioGD" %in% dev_name
 }
 
+# If the current device is null, try to open the default device
+# infer what it'll be
+infer_device <- function() {
+  if (!is_null_device()) {
+    return(.Device)
```
Comment (cpsievert) [inline R/utils.R:94]: Use `dev.cur()` instead of `.Device`

File: R/utils.R [hunk 3]
```diff
@@ -83,10 +83,90 @@ is_rstudio <- function(version_needed = NULL) {
...
+  dev_before <- dev.cur()
+  res <- try(dev_fun(filename = tmp))
+  if (inherits(res, "try-error")) {
+    maybe_warn(
+      "thematic tried but failed to open a graphics device. If plots don't render ",
+      "how you'd expect them to, try setting `options(device = ...)` to a device ",
+      "that is supported on your system (e.g., `png`, `jpeg`, `Cairo::Cairo`, etc).",
+      id = "no-graphics-device"
+    )
+    return(dev_before)
```
Comment (cpsievert) [inline R/utils.R:133]:
```suggestion
    return(NULL)
```

File: R/hooks.R [hunk 4]
```diff
@@ -148,92 +148,58 @@ can_render <- function(family, type = c("base", "grid"), dev_fun, dev_name) {
...
-    dev.off(dev_after)
-    unlink(tmp, recursive = TRUE)
-    dev.set(dev_before)
-  }, add = TRUE)
-  names(dev_after)
-}
-
 # Do our best to map the name of the current device to an
 # actual device function
 get_device_function <- function(name) {
```
Comment (cpsievert) [inline R/hooks.R:188]:
```suggestion
get_device_function <- function(name = infer_device()) {
```

File: R/base.R [hunk 5]
```diff
@@ -47,25 +47,22 @@ base_params_set <- function(theme = .globals$theme) {
...
-  dev_after <- dev.cur()
-  if (dev_before != dev_after) {
-    dev.off(dev_after)
-    dev.set(dev_before)
+attempt_palette <- function(...) {
+  if (is_null_device()) {
+    attempt_with_new_device(palette(...))
+  } else {
+    palette(...)
   }
```
Comment (schloerke) [inline R/base.R:67]: If more methods come around in the future, it might be worth doing a wrapper method to avoid duplication

```r
attempt_ <- function(code) {
  if (is_null_device()) {
    attempt_with_new_device(code)
  } else {
    force(code)
  }
}
attempt_par <- function(...) {
  attempt_(par(...))
}
```

**Review by schloerke — APPROVED** [review]

**Comment by cpsievert** [comment]
Merging before tests run since GHA is down
